### ISSUE TITLE
jdk7-oracle (and potentially others) should apt-get update before apt-get install python-software-properties

### ISSUE THREAD

**Issue by centic9** [Krijger/docker-cookbooks#7]
The version of this package in the apt-caches in the image is not available any more for ubuntu, the line should probably read:

> RUN apt-get update && apt-get -y install python-software-properties

to ensure that the latest version of this package is installed.

The following files are affected: https://github.com/Krijger/docker-cookbooks/search?utf8=%E2%9C%93&q=python-software-properties

Similar issues exist for other apt-get install steps in the following Dockerfiles
- docpad
- firefox-jenkins-slave 
- tomcat7
- dind-jenkins-slave
- mongo

**Comment by Krijger** [comment]
These images depend on the `supervisor` image. The idea for this repository is that `apt-get update` is always run in the top image (i.e. supervisor).
If you are building locally, you should also build the `suporvisor` image first. That's also the reason for the build_all.sh script in the root of the project.

Does that take care of your problem?

**Comment by centic9** [comment]
Ok, didn't see that, a build of the supervisor-image is available on the docker registry and so I tried to only apply the jdk7 one on top of it.
